### PR TITLE
Use jsdelivr cdn for resources

### PR DESCRIPTION
**Pull request by sunnylqm**
To improve the life for developers from some country

### CODE REVIEW

**Comment by IjzerenHein** [comment]
@ide What are your thoughts on this?

**Comment by ide** [comment]
Seems fine and shouldn’t cause any changes for the same-origin policy. One question I have is: what issues does Cloudflare have that jsdelivr doesn’t?

**Comment by IjzerenHein** [comment]
@sunnylqm Can you share some resources/proof that jsdelivr outperforms cloudflare for you?

**Comment by ide** [comment]
It could be that jsdelivr has an ICP license for China (https://www.jsdelivr.com/network), while cdnjs maybe doesn't use one (even though Cloudflare does have the technical capability for businesses w/the license).

**Comment by sunnylqm** [comment]
That's right. The only global cdn that is working in China.

**Comment by ide** [comment]
Seems fine to me - @IjzerenHein could you take care of this?

**Comment by IjzerenHein** [comment]
This has been merged in the main repo, thank you all!

**Pull request closed without merging**
